server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gfjgabriel/ead-config-server-repo
          default-label: main

ead:
  configServer:
    username: configserver
    password: configserver
  serviceRegistry:
    username: serviceregistry
    password: serviceregistry

eureka:
  client:
    service-url:
      defaultZone: http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka/

  instance:
    hostname: localhost